[package]
name = "add_uefi_boot"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.11"
kernel = { path = "..", artifact = "bin", target = "x86_64-unknown-none" }

[build-dependencies]
kernel = { path = "..", artifact = "bin", target = "x86_64-unknown-none" }
